[versions]
fabric-api = "0.107.0+1.21.1"
fabric-kotlin = "1.11.0+kotlin.2.0.0"
fabric-loader = "0.16.9"
fabric-loom = "1.8-SNAPSHOT"
kotlin = "2.0.21"
minecraft = "1.21.1"
slf4j = "2.0.16"
yarn-mappings = "1.21.1+build.3"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
yarn-mappings = { module = "net.fabricmc:yarn", version.ref = "yarn-mappings" }

[bundles]

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
